/** @jsxImportSource @emotion/react */
import React from 'react'
import { css } from '@emotion/react'
import Head from 'next/head'

export default function Home() {
  const color = 'darkgreen'
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Ultimate Next App</main>
      <div
        css={css`
          background-color: hotpink;
          &:hover {
            color: ${color};
          }
        `}
      >
        This has a hotpink background.
      </div>
    </>
  )
}
